### ISSUE TITLE
get_fixture 

### ISSUE THREAD

**Issue by simonpreynolds** [jimmyday12/fitzRoy#110]
It appears that get_fixture(year) may be broken. Potentially the recent change to footywire-calcs.R and line 171 (tidyr::nest(data = -c(.data$Round)) %>%) may be relevant.

```` r
library(fitzRoy)
#> Registered S3 method overwritten by 'rvest':
#>   method            from
#>   read_xml.response xml2
afl_data_1998_2018 <- get_afltables_stats(start_date = "1998-01-01", end_date = "2018-11-25")
#> Returning data from 1998-01-01 to 2018-11-25
#> Finished getting afltables data
fixture <- get_fixture(season = 2019)
#> Error in -c(.data$Season): invalid argument to unary operator
```

<sup>Created on 2020-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimmyday12** [comment]
@simonpreynolds - I can't replicate this one. Do you know what version you have installed? 

Are you able to print out the results of `devtools::session_info()`

**Comment by simonpreynolds** [comment]
I could see where this was going, so rebuilt the environment. I have now got get_fixture to work. My apologies - it was very weird that all functions but get_fixture would work. Anyway, please feel free to close this issue.

Simon
