### ISSUE TITLE
get_footywire_betting_odds raises error on empty data set

### ISSUE THREAD

**Issue by cfranklin11** [jimmyday12/fitzRoy#112]
Requesting betting odds for a season that doesn't have any yet (e.g. 2020 while we're still in January) raises an error from the internals of `get_footywire_betting_odds`. It would be better for the function to return an empty data frame instead.

I almost have a fix ready, so PR forthcoming.

The code below will raise the error:

```r
fitzRoy::get_footywire_betting_odds(start_season = 2020, end_season = 2020)
```

**Comment by mgpullen** [comment]
FYI, running the code in cfranklin11's original post still results in an error even though we are now 8 or so rounds into the season.
