### ISSUE TITLE
update CRAN version

### ISSUE THREAD

**Issue by dicook** [jimmyday12/fitzRoy#117]
Would you be able to update the version of CRAN. I don't see much difference, but  the CRAN version    fails on:

> library(fitzRoy)
> aflw <- get_aflw_match_data(start_year = 2018)
Error: Column `year` not found in `.data`

but the github version works.

**Comment by jimmyday12** [comment]
@dicook This was submitted and accepted over the weekend to CRAN cc @anoafl 

https://CRAN.R-project.org/package=fitzRoy
