### ISSUE TITLE
Create function to return player data

### ISSUE THREAD

**Issue by jimmyday12** [jimmyday12/fitzRoy#141]
It has often been requested that we include things like DOB in the package. 

For example - https://github.com/jimmyday12/fitzRoy/issues/60

I think this almost could be it's own function to just return that data. I have to think about how this is returned since it isn't a season/round thing so it will be a little different to the normal `fetch_` functions. 

It could be that you provide either a set of names, a team or a season (or some combination).

```
fetch_player_info(season = 2021, team = "HAW", names = NULL, source = "AFL", comp = "AFLW")
```

Essentially - we would search for any unique players who match the season/team/names arguments and return general information like DOB. 

If any of season/team/names is NULL, it is ignored.

**Comment by audas** [comment]
Hi, I was wondering if there was any progress or further thought on this? I am looking to do some data analysis on player ages and this would be REALLY handy.

Being able to select by team would be good outside of fetch_player_info as a thought.

DOB, Height, Debut appear to be fixed - weight may change?

**Comment by jimmyday12** [comment]
This is now done with the release of v1.1.0 and the `fetch_player_details_` set of functions
