### ISSUE TITLE
failed to download 2021 afl tabs data due to data conversion error

### ISSUE THREAD

**Issue by SingSing2020** [jimmyday12/fitzRoy#149]
---
The following error occurs when trying to download the 2021 afl tabs data, 2020 works as expected  
Error: Can't combine `Round` character and `Round` double.

```r
# 2021 season
AFL_gameday_Stats_current_Season <- fetch_player_stats_afltables(2021)

# 2020 ""
AFL_gameday_Stats_current_Season <- fetch_player_stats_afltables(2020)
```

**Comment by cfranklin11** [comment]
@jimmyday12 I have a fix for this that should be ready for PR before end of day. It also includes a fix for `fetch_ladder_afl` that was required to get the tests to pass.
