### ISSUE TITLE
Add 'Replace Venues' function

### ISSUE THREAD

**Issue by jimmyday12** [jimmyday12/fitzRoy#15]
Footywire venues are named differently to afltables. Write a function people can use to convert them

**Comment by cfranklin11** [comment]
If you're not actively working on this, I already have a complete hash map for this that I've been using and would be happy to open a PR.

**Comment by jimmyday12** [comment]
Hi @cfranklin11 - sorry I never replied to this but yep, happy for a PR here!

**Comment by cfranklin11** [comment]
No worries. I noticed that the `replace_teams` function is applied across all data sources and seems to convert all team names to AFLTables conventions. Did you have something similar in mind for a `replace_venues` function? I think that's probably the best approach, but wanted to make sure.
