### ISSUE TITLE
2021 AFL Tables Function Error

### ISSUE THREAD

**Issue by petebish07** [jimmyday12/fitzRoy#151]
Hi, I'm getting the following error when trying to use the fetch_player_stats_afltables function on the 2021 season, other seasons appear to be fine.

Below is rundown, hopefully everything you need is there.

Also, thanks for creating and maintaining this package, it's unreal.

Test <- fetch_player_stats_afltables(season = 2021)
i Looking for data from 2021-01-01 to 2021-03-23
v fetching cached data from <github.com> ... done
i New data found for 9 matches
v Downloading data ... done
i Processing XMLSError: Can't combine `Round` <character> and `Round` <double>.
Run `rlang::last_error()` to see where the error occurred.
x Processing XMLS ... failed
> rlang::last_error()
<error/vctrs_error_incompatible_type>
Can't combine `Round` <character> and `Round` <double>.
Backtrace:
  1. fitzRoy::fetch_player_stats_afltables(season = 2021)
  5. purrr::map2_dfr(., .y = start:end, ~dplyr::mutate(., Season = .y))
  6. dplyr::bind_rows(res, .id = .id)
  7. vctrs::vec_rbind(!!!dots, .names_to = .id)
  9. vctrs::vec_default_ptype2(...)
 10. vctrs:::vec_ptype2_df_fallback(x, y, opts)
 11. vctrs:::vec_ptype2_params(...)
 12. vctrs:::vec_ptype2_opts(x, y, opts = opts, x_arg = x_arg, y_arg = y_arg)
 14. vctrs::vec_default_ptype2(...)
 15. vctrs::stop_incompatible_type(...)
 16. vctrs:::stop_incompatible(...)
 17. vctrs:::stop_vctrs(...)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/vctrs_error_incompatible_type>
Can't combine `Round` <character> and `Round` <double>.
Backtrace:
     x
  1. +-fitzRoy::fetch_player_stats_afltables(season = 2021)
  2. | \-fitzRoy:::scrape_afltables_match(urls)
  3. |   \-fitzRoy:::get_afltables_player_ids(min(games_cleaned$Season):max(games_cleaned$Season))
  4. |     \-`%>%`(...)
  5. \-purrr::map2_dfr(., .y = start:end, ~dplyr::mutate(., Season = .y))
  6.   \-dplyr::bind_rows(res, .id = .id)
  7.     \-vctrs::vec_rbind(!!!dots, .names_to = .id)
  8.       \-(function () ...
  9.         \-vctrs::vec_default_ptype2(...)
 10.           \-vctrs:::vec_ptype2_df_fallback(x, y, opts)
 11.             \-vctrs:::vec_ptype2_params(...)
 12.               \-vctrs:::vec_ptype2_opts(x, y, opts = opts, x_arg = x_arg, y_arg = y_arg)
 13.                 \-(function () ...
 14.                   \-vctrs::vec_default_ptype2(...)
 15.                     \-vctrs::stop_incompatible_type(...)
 16.                       \-vctrs:::stop_incompatible(...)
 17.                         \-vctrs:::stop_vctrs(...)
>

**Comment by jimmyday12** [comment]
Thanks for the info. 

I have a feeling this may have been fixed by a recent PR - https://github.com/jimmyday12/fitzRoy/commit/8767ccb46116e91b81cbf0e001ffb8488eb1194a

It sounds similar to this issue which is now closed - https://github.com/jimmyday12/fitzRoy/issues/149

You'll have to reinstall the package with the dev version 
`devtools::install_github("jimmyday12/fitzRoy")`

Let me know if that fixes the problem!

**Comment by petebish07** [comment]
Yep, that solved it. Thanks for replying so quick

**Comment by jimmyday12** [comment]
Fixed by https://github.com/jimmyday12/fitzRoy/commit/8767ccb46116e91b81cbf0e001ffb8488eb1194a
