### ISSUE TITLE
Unable to install package devtools::install_github("jimmyday12/fitzRoy")

### ISSUE THREAD

**Issue by nandania-sportsbet** [jimmyday12/fitzRoy#152]
> devtools::install_github("jimmyday12/fitzRoy")
[2021-04-08T03:23:44.192Z] [91mError: Failed to install 'unknown package' from GitHub:
[2021-04-08T03:23:44.192Z]   HTTP error 404.
[2021-04-08T03:23:44.192Z]   No commit found for the ref master
[2021-04-08T03:23:44.192Z] 
[2021-04-08T03:23:44.192Z]   Did you spell the repo owner (`jimmyday12`) and repo name (`fitzRoy`) correctly?
[2021-04-08T03:23:44.192Z]   - If spelling is correct, check that you have the required permissions to access the repo.
[2021-04-08T03:23:44.192Z] Execution halted

**Comment by nandania-sportsbet** [comment]
Actually trying to resolve Error: Column `Jumper.No.` can't be converted from numeric to character in prod 
so while fixing wanted to install package again so got above error
Actually still using "get_afltables_stats" api

**Comment by jimmyday12** [comment]
I assume this has worked in the past for you? I suspect that is an error with `devtools` rather than anything to do with `fitzRoy`. I certainly can't replicate on my machine or test cases. 

I would suggest re-installing `devtools` and trying again. It is actually the package `remotes` that handles this, so you might want to also re-install that (although, re-installing `devtools` should handle that). And if that doesn't fix it, perhaps logging an issue over there if it isn't working https://github.com/r-lib/remotes

**Comment by nandania-sportsbet** [comment]
@jimmyday12 Thanks for replying so quick
Actually i even tried with install.packages("fitzRoy") and then it complains about following
Error in library("fitzRoy") : there is no package called ‘fitzRoy’

**Comment by jimmyday12** [comment]
That sounds like an error with your machine and maybe R library. Can you install/load other packages from either github or CRAN?

**Comment by nandania-sportsbet** [comment]
FROM rocker/r-ver:3.6.0
RUN apt-get update \
    && apt-get install -y cron libxml2-dev zlib1g-dev libcurl4-gnutls-dev libssl-dev awscli \
    && R -e 'install.packages("rsconnect")' \
    && R -e 'install.packages("devtools")' \
   && R -e 'install.packages("fitzRoy")' \
    && R -e 'install.packages(c("data.table"))' \
    && R -e 'install.packages("base64enc")' \
    && R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/rlang/rlang_0.3.1.tar.gz", repos=NULL, type="source", INSTALL_opts = c("--no-lock"))' \
    && R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/tibble/tibble_2.0.1.tar.gz", repos=NULL, type="source", INSTALL_opts = c("--no-lock"))' \
   && R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/dplyr/dplyr_0.8.0.1.tar.gz", type="source", INSTALL_opts = c("--no-lock"))'

**Comment by nandania-sportsbet** [comment]
I am trying above in docker file and when i run R script in container get following error : 
Error in library("fitzRoy") : there is no package called ‘fitzRoy’

**Comment by nandania-sportsbet** [comment]
I am new to R your help is appreciated. Thanks

**Comment by jimmyday12** [comment]
I don't really know anything about docker but it looks like you need to install fitzRoy in that docker file? Adding the following line maybe?

```&& R -e 'install.packages("fitzRoy")' ```

Again - I don't know much about docker so have no idea if this is actually what you need
