### ISSUE TITLE
Scores for 2017 PA v WC EF exclude Extra Time 

### ISSUE THREAD

**Issue by TonyCorke** [jimmyday12/fitzRoy#155]
Please briefly describe your problem and what output you expect. 

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
Home.score and Away.score for 2017 EF between PA and WC are both 60. That is the score at the end of regulation time. The final score, after ET was 76-78
```r
library(fitzRoy)
library(dplyr)

dat <- get_afltables_stats(start_date = "2017-01-01", end_date = "2017-12-31")

dat %>% filter(Round == "EF", Season == "2017", Home.team == "Port Adelaide") %>% select(Home.score, Away.score)
```

**Comment by jimmyday12** [comment]
https://github.com/jimmyday12/fitzRoy/pull/223
