### ISSUE TITLE
missing height & weights, time on Ground > 100 %

### ISSUE THREAD

**Issue by SingSing2020** [jimmyday12/fitzRoy#163]
---

height & weights has 3,400 NA values 
numerious players have time-on-ground > 100% in 2020 season

```r
afl_adv_GameDay_stats_2018_2021 <- fetch_player_stats_fryzigg(2018:2021)

summary(afl_adv_GameDay_stats_1993_2021)

``
`

**Comment by jimmyday12** [comment]
This is related to the dataset from @Fryzigg so will need him to take a look

**Comment by SingSing2020** [comment]
it appears that the %'s are simply inflated by the number of minutes lost in the 2020 season. Can be fixed with the below calc.
TOG_2020 - (TOG * .2) @Fryzigg

**Comment by SingSing2020** [comment]
Looks like the TOG is now fine, thanks guys @jimmyday12 @Fryzigg
