### ISSUE TITLE
Data input error for player IDs from AFL Tables

### ISSUE THREAD

**Issue by jaidenpopowski** [jimmyday12/fitzRoy#168]
Using 2021 data from AFL Tables gives two IDs for Eddie Ford (NM) and no ID for Brayden Cook (Adel). Eddie Ford has IDs 12922 AND 12932 and has replaced Brayden Cook's statistics wearing number 15 for the Crows.

![EddieFord](https://user-images.githubusercontent.com/98011675/150082605-c87fff12-a1db-475c-8c26-d5a2eff7db2d.png)

---

```r
afltables %>%
  select(season, round,date,first_name,surname,id,playing_for,jumper_no) %>%
  filter(first_name == "Eddie", surname == "Ford")
afltables %>%
  select(season, round,date, first_name,surname,id,playing_for, jumper_no) %>%
  filter(first_name == "Brayden", surname == "Cook")
```

**Comment by broccoli29586** [comment]
Just come across the same thing. @jimmyday12 bugfix soon?

**Comment by jimmyday12** [comment]
I'm going to try take a look at this one this weekend. These bugs in the legacy data are always tricky to nail down
