### ISSUE TITLE
Goal Assists Stat

### ISSUE THREAD

**Issue by Jack-FG** [jimmyday12/fitzRoy#18]
Hi Gents,

It appears that the 'goal assists' stat is missing from fitzroy. Appears between Hit outs and inside 50s on the footywire website. But does not get dragged through in fitzroy.

**Comment by anoafl** [comment]
Hi Jack, 

Try
fitzRoy::afldata, should have goal assists up until 2017 while we work on this issue. 

Have a great day, 

Rob

**Comment by Jack-FG** [comment]
Hi Rob,

All good mate. Just thought I would point it out...definetly in no rush.

Thanks for the direction re.  afldata

You to!

**Comment by Jack-FG** [comment]
I probably should have clarified in saying that it does not come through when using update_footywire_stats()

**Comment by jimmyday12** [comment]
Thanks @Jack-AFL! I'm going to try give this a look this week. Will let you know once it's fixed

**Comment by jimmyday12** [comment]
@Jack-AFL This should be fixed. You may have to reinstall. Let me know how you go!
