### ISSUE TITLE
fetch_lineup_afl for new AFLW Season

### ISSUE THREAD

**Issue by jt026** [jimmyday12/fitzRoy#184]
just wondering how we can fetch upcoming lineups for this new AFLW Season given its also in 2022 like last seasons.

**Comment by jimmyday12** [comment]
Just pushed an update that should fix this. It's hard to handle but now using `season = 2022` will return both seasons. You'll have to filter it after returning the data to just get the upcoming season

**Comment by jargreen** [comment]
hey just wondering if you'll also be updating this to include player stats for season 7 2022. currently only season 6 data is available.

**Comment by dbmurray** [comment]
Hrm. fetch_fixture_afl(2022, comp = "AFLW") will return both 2022 season, but I can't seem to get the same outcome when I try fetch_player_stats(2022, comp = "AFLW", source = "fryzigg") which only returns season 6 data. 

Perhaps its the source (i.e fryzigg)?

**Comment by jt026** [comment]
fetch_player_stats(season = 2022, round_number = 10, comp = "AFLW", source = "AFL")
should work
