### ISSUE TITLE
Incorrect venues on AFL Tables

### ISSUE THREAD

**Issue by JaseZiv** [jimmyday12/fitzRoy#195]
Have noticed this is issue stems from the data on the AFL Tables website, however some match venues are incorrect.

For the reprex provided, the results have GWS playing Richmond at Docklands, yet they actually played at Spotless. Additionally, GC vs Essendon listed as being played at Kardinia Park. Using version `1.3.0`:
---

```r
wrong_venues <- fetch_results(season = 2021, round_number = 22, source = "afltables")
```

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/31471783/222292225-6383fbfa-9bf7-4a74-a908-615a369dbe55.png">

Don't know how far and wide this issue stems from, but thought I'd raise here as a starting point for anyone wanting to investigate and correct the stored data.

**Comment by JaseZiv** [comment]
So sorry - my bad - on further digging, it appears that this did in fact happen:

![image](https://user-images.githubusercontent.com/31471783/222309132-94e55468-e28a-487f-bdf8-3e6bdd2f77fe.png)

Guess that was COVID/lockdowns-related?

**Comment by peteowen1** [comment]
This can be closed
