### ISSUE TITLE
fetch_player_details_afl currently returning no data for all seasons

### ISSUE THREAD

**Issue by peteowen1** [jimmyday12/fitzRoy#206]
fetch_player_details_afl currently is returning no data for all seasons.

![image](https://github.com/jimmyday12/fitzRoy/assets/15244843/04b6a85b-ddbe-4f3e-af09-cc5bf48347c4)

This is because the fetch_teams_afl function is currently having an issue where it filters out all rows with an NA in any column - but new metadata has been added to these tables which often has multiple NA values.

A fix has been suggested in the pull request below

https://github.com/jimmyday12/fitzRoy/pull/205

**Comment by jimmyday12** [comment]
Linked PR closes this

**Comment by databatch** [comment]
I am encountering the same issue

```r
> fitzRoy::fetch_player_details_afl(2020,
+                                   team = NULL,
+                                   comp = "AFLM",
+                                   official_teams = FALSE)
# A tibble: 0 × 1
# ℹ 1 variable: data_accessed <date>
```
