### ISSUE TITLE
Incorrect hitout data from download

### ISSUE THREAD

**Issue by liam-crow** [jimmyday12/fitzRoy#214]
When comparing hitout data from the cached dataset to the source from afltables.com I noticed quite a few inconsistencies

Please view the following tweet to see examples of incorrect data
![GMjYrtCaEAAoNnP](https://github.com/jimmyday12/fitzRoy/assets/52619113/2d43bbdb-7ad7-4bda-87f3-837ab4c59b79)

https://twitter.com/UselessStatsAFL/status/1785916078838956375

**Comment by peteowen1** [comment]
Checked this and yeah it just seems like some data is wrong for whatever reason in the file:
https://github.com/jimmyday12/fitzRoy_data/raw/main/data-raw/afl_tables_playerstats/afldata.rda

@jimmyday12 
if you do a single run of the weekly-scrape-playerstats-afltables.R script but change it to scrape everything (not ideal if you were doing this every week but obviously fine for a one-off fix) then that fixes this issue.

Only bit of the weekly script you would need to change for this one-off would be 

afldata_new <- fetch_player_stats_afltables(1897:end_year, 
                                            rescrape = TRUE, 
                                            rescrape_start_season = 1897)

After you run that script, the afldata file has hitout numbers matching the right screenshot as required.

**Comment by jimmyday12** [comment]
https://github.com/jimmyday12/fitzRoy/pull/223
