### ISSUE TITLE
Implement function to add weather data

### ISSUE THREAD

**Issue by jimmyday12** [jimmyday12/fitzRoy#22]
Need to have a function to grab weather data. The current example just pulls from a sample scrape we did for 2017. Ideally we would have something like 

`get_weather_data(match_id = 1)`
`get_weather_data(dates = "2018-05-10")`

where those parameters could be single values or vectors.

**Comment by srepho** [comment]
Happy to help out implementing this feature as your package has been really useful. Have you just taken the daily rainfall for nearest weather station to the ground?

**Comment by jimmyday12** [comment]
Thanks @srepho! 

I haven't thought too much about this one. 

@anoafl did the initial scrape so may have some thoughts but also talked to someone at the useR conference who had some ideas. 

I'm keen to make it a function that doesn't require any hosting of data by us and simply allows users to do their own scrape to get the weather for a particular match

**Comment by srepho** [comment]
No problem - I will work on some possible solutions over next few weeks and come back with a pull request. Might also ask AFL Tables if it's something they would want to add to their database? That way could just add on to the functionality you guys already have.

**Comment by OscarLane** [comment]
FYI, I've been working on adding in AFL womens stats to the package, and came across the following fields from the official AFL stats site, which are available for all matches:
```
$ score.weather.description                 <chr> "Clear", "Rain at times", "Partly ...
$ score.weather.tempInCelsius               <dbl> 18, 18, 18, 18
$ score.weather.weatherType                 <chr> "CLEAR_NIGHT", "RAIN", "RAIN", "RAIN"
```
I'll definitely pull these down for womens stats as it looks like there's demand, but it should also be possible to get these for the mens games as the site structure looks pretty similar to the womens site.

**Comment by jimmyday12** [comment]
This is now in the AFL data
