### ISSUE TITLE
Fryzigg data not up to date after Round 13

### ISSUE THREAD

**Issue by RL98** [jimmyday12/fitzRoy#221]
The fetch player stats from fryzigg function appears to have missing data post Round 13 when trying to get fryzigg data. Unsure if this is an ongoing issue or data refresh issue for just last week. 

Cheers

**Comment by mattm14** [comment]
There appears to be no data at all after Round 12. Will this be updated?

**Comment by jimmyday12** [comment]
Just wanted to note that the package is returning the most up to date data from @Fryzigg website and is working as expected. I don't update or have any control over that data - would need @Fryzigg to comment on if he plans to keep it up to date moving forward

**Comment by mattm14** [comment]
@jimmyday12 thanks for confirming.

@Fryzigg as the last game that appears currently is from Rd 12, will the data be kept up to date moving forward?

**Comment by Fryzigg** [comment]
Just returned from 2-ish weeks in Japan. Service crashed trying to process the WCE vs NM game due to an uncaught exception processing Jack Hutchinson (didn't exist in the player lookup database due to mid-season draft), Unfortunate timing to not have easy access to a PC to debug

**Comment by mattm14** [comment]
thanks for the update @Fryzigg , much appreciated.
