### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Statsman10** [jimmyday12/fitzRoy#24]
After running devtools::install_github("jimmyday12/fitzRoy")
the file downloads but when installing an error occurs:
Installation failed: command failed (1)
there is a reference to "C:/PROGRA~1/R/R-34~1.2/bin/i386/Rterm.exe" not found

**Comment by jimmyday12** [comment]
Hey mate - I can't replicate here so can you run sessionInfo() and send the output of that, as well as pasting the whole error message?

Assuming you've also installed devtools first? 
`install.packages("devtools")`

**Comment by Statsman10** [comment]
Hi James,
Thank you for the reply.

Yes devtools is installed:

> install.packages("devtools")
Installing package into ‘C:/Users/wojte/OneDrive/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/devtools_1.13.6.zip'
Content type 'application/zip' length 445100 bytes (434 KB)
downloaded 434 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\wojte\AppData\Local\Temp\RtmpKMN0p0\downloaded_packages
sessionInfo() gives:

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.2  R6_2.2.2        tools_3.4.2     withr_2.1.2    
 [6] curl_3.2        memoise_1.1.0   git2r_0.21.0    digest_0.6.15   devtools_1.13.6

The full installation is:

> devtools::install_github("jimmyday12/fitzRoy")
Downloading GitHub repo jimmyday12/fitzRoy@master
from URL https://api.github.com/repos/jimmyday12/fitzRoy/zipball/master
Installing fitzRoy
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/wojte/AppData/Local/Temp/RtmpKMN0p0/devtools30c413fcfd/jimmyday12-fitzRoy-5c56d75"  \
  --library="C:/Users/wojte/OneDrive/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'fitzRoy' ...
** R
** data
*** moving datasets to lazyload DB
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Error in system2(if (nzchar(arch)) file.path(R.home(), "bin", arch, "Rterm.exe") else file.path(R.home("bin"),  : 
  '"C:/PROGRA~1/R/R-34~1.2/bin/i386/Rterm.exe"' not found
* removing 'C:/Users/wojte/OneDrive/Documents/R/win-library/3.4/fitzRoy'
Installation failed: Command failed (1)


Regards,
Wojtek

**Comment by Statsman10** [comment]
I have managed to get it installed on my Mac and running fine on there.
Thanks.

**Comment by jimmyday12** [comment]
Hey mate - ok cool. I'll keep an eye on this (it may be a Windows issue) but it's a bit beyond my knowledge! Might be an R installation issue. Did a quick search but couldn't see anything similar out there
