### ISSUE TITLE
fetch_player_stats_afltables Missing Games from 2024

### ISSUE THREAD

**Issue by TonyCorke** [jimmyday12/fitzRoy#243]
---

fetch_player_stats_afltables(season = 2024) does not return last three games of AFLTables Round 23

```r
library(fitzRoy)
library(dplyr)

dat = fetch_player_stats_afltables(season = 2024)

dat %>% filter(Round == 23, Home.team == "Carlton" | Away.team == "Carlton") # returns nothing
dat %>% filter(Round == 23, Home.team == "Adelaide" | Away.team == "Adelaide") # returns nothing
dat %>% filter(Round == 23, Home.team == "Hawthorn" | Away.team == "Hawthorn") # returns nothing

dat %>% filter(Round == 23, Home.team == "Sydney" | Away.team == "Sydney") #returns as expected
```

**Comment by jimmyday12** [comment]
I'll take a look - I suspect the cached data just hasn't updated and the logic for identifying missing games isn't working. 

In the interim, this fixes things

```
fetch_player_stats_afltables(season = 2024, rescrape = TRUE, rescrape_start_season = 2024)
```

**Comment by TonyCorke** [comment]
Thanks James,

That certainly picks up most of the missing data, but we have NA IDs for
the debutants (as we do for those in Round 24).

Ta for your quick response,

Tony
