### ISSUE TITLE
Error using get_afltables_stats for dates after 29/7/2018

### ISSUE THREAD

**Issue by Cam74** [jimmyday12/fitzRoy#33]
Hi, I'm not having any issues with dates up to and including "2018-07-29" but get an error for any dates after that?

Appreciate your help!

Thanks,
Cam

===========================================================

> statsadd <- get_afltables_stats(start_date = "2018-05-01", end_date = "2018-07-29")
Returning data from 2018-05-01 to 2018-07-29
Finished getting afltables data
> statsadd <- get_afltables_stats(start_date = "2018-08-01", end_date = "2018-08-18")
Returning data from 2018-08-01 to 2018-08-18
Downloading data

|==========================================================================================================================================|100% ~0 s remaining     

Finished downloading data. Processing XMLs

Error: 'str_squish' is not an exported object from 'namespace:stringr'

**Comment by jimmyday12** [comment]
Thanks for the message @Cam74! 

Seems like your version of `stringr` doesn't have `str_squish` as part of it, which is an oversight of my package. If that's the case, I'll add the minimum version into the package which should fix that problem. 

Are you able to send me the output of `packageVersion("stringr")` just to be certain. If it's below 1.3.0 then an interim fix will be to update that specific package using `install.packages("stringr")` until I push a new version of `fitzRoy`

**Comment by Cam74** [comment]
Thanks a lot for the quick reply.  See below - I have version 1.2.0.
I also tried running the install.packages("stringr"), and it stayed 1.2.0?

Appreciate your help.

See below...

> packageVersion("stringr")
[1] ‘1.2.0’
> install.packages("stringr")
Installing package into ‘C:/Users/camer/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://mran.microsoft.com/snapshot/2017-09-01/bin/windows/contrib/3.4/stringr_1.2.0.zip'
Content type 'application/zip' length 149289 bytes (145 KB)
downloaded 145 KB

package ‘stringr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\camer\AppData\Local\Temp\RtmpGQ4X6Z\downloaded_packages
> statstest <- get_afltables_stats(start_date = "2018-08-01", end_date = "2018-08-24")
Error in get_afltables_stats(start_date = "2018-08-01", end_date = "2018-08-24") : 
  could not find function "get_afltables_stats"
> library(fitzRoy)
> statstest <- get_afltables_stats(start_date = "2018-08-01", end_date = "2018-08-24")
Returning data from 2018-08-01 to 2018-08-24
Downloading data

|==========================================================================================================================================|100% ~0 s remaining     

Finished downloading data. Processing XMLs

Error: 'str_squish' is not an exported object from 'namespace:stringr'
> packageVersion("stringr")
[1] ‘1.2.0’

**Comment by Cam74** [comment]
It's ok, I think I've figured it out. 
After some googling, I used:

install.packages("stringr", repos='http://cran.us.r-project.org')

Now I have version 1.3.1 and it all seems to be working.
Thanks for your help.  Appreciate it.
