### ISSUE TITLE
Suggestion: ungroup the result from get_afltables_stats()

### ISSUE THREAD

**Issue by neilfws** [jimmyday12/fitzRoy#38]
get_afltables_stats() returns a tibble grouped by Season, Round, Home.team, Away.team.

I would suggest that the function should include `ungroup()` as the last step before returning results. It isn't clear to the end user that the output is grouped unless they inspect the tibble, and grouping may have unintended consequences in any code that the user writes which uses the tibble.

**Comment by jimmyday12** [comment]
Thanks @neilfws, I agree. There are a few inconsistencies like that I'd like to fix up. Open to PR if you are interested, otherwise I'll take a look over the next week and keep you posted.
