### ISSUE TITLE
Leverage existing functions for Rating systems

### ISSUE THREAD

**Issue by Lingtax** [jimmyday12/fitzRoy#43]
One of the development targets is ELO ratings. In the interim, could you add a vignette that uses an existing package like [PlayerRatings](https://cran.r-project.org/web/packages/PlayerRatings/PlayerRatings.pdf)?

**Comment by jimmyday12** [comment]
@Lingtax Sorry I missed this when you submitted it. For sure, that would be a relatively easy addition. I'll aim to get one before the AFLW season starts
