### ISSUE TITLE
Warnings returned when using get_afltable_stats

### ISSUE THREAD

**Issue by insightlane** [jimmyday12/fitzRoy#44]
When using get_afltable_stats, the following warnings are returned:

> get_afltables_stats(start_date = "1897-05-07", end_date = Sys.Date())
Returning data from 1897-05-07 to 2018-10-02
Downloading data

|===================================================================================================|100% ~0 s remaining     
Finished downloading data. Processing XMLs

Warning: 396 parsing failures.
row # A tibble: 5 x 5 col     row col   expected   actual file                                             expected   <int> <chr> <chr>      <chr>  <chr>                                            actual 1  8713 Round an integer QF     'https://afltables.com/afl/stats/2018_stats.txt' file 2  8714 Round an integer QF     'https://afltables.com/afl/stats/2018_stats.txt' row 3  8715 Round an integer QF     'https://afltables.com/afl/stats/2018_stats.txt' col 4  8716 Round an integer QF     'https://afltables.com/afl/stats/2018_stats.txt' expected 5  8717 Round an integer QF     'https://afltables.com/afl/stats/2018_stats.txt'
... ................................. ... ....................................... [... truncated]
Finished getting afltables data
Warning messages:
1: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)
2: Unknown columns: `Substitute`

**Comment by jimmyday12** [comment]
Thanks again @insightlane - Probably related to #45
