### ISSUE TITLE
Should 'fixture' now have 2019 games?

### ISSUE THREAD

**Issue by joffa101** [jimmyday12/fitzRoy#50]
---

Fixture still has 2018 games. Should it now have 2019 games?

```r
View(fixture)
--
 
  |  
 

```

**Comment by jimmyday12** [comment]
Ah yes, I suspect that I need to update this code. I'll take a look this week. Thanks

**Comment by jimmyday12** [comment]
Updated in 93108eb1895f6f7afcdcc4c82842a1bd9b92daeb
