### ISSUE TITLE
I have the footywire abbreviation descriptions 

### ISSUE THREAD

**Issue by joffa101** [jimmyday12/fitzRoy#51]
Hi,

I was getting the footywire abbreviation descriptions for my own references. I have pasted them here if you want to add them to the reference section. 

AF AFL Fantasy Points 
B Behinds 
BO Bounces 
CCL Centre Clearances 
CG Clangers 
CL Clearances 
CM Contested Marks 
CP Contested Possessions 
D Disposals 
DE Disposal Efficiency % 
ED Effective Disposals 
FA Frees Against 
FF Frees For 
G Goals 
GA Goal Assists 
GA1 Goal Assists on Advance Page
HB Handballs 
HO Hit Outs 
I50 Inside 50 
ITC Intercepts 
K Kicks 
M Marks 
MG Metres Gained 
MI5 Marks Inside 50 
Match_id Match ID 
One.Percenters One Percenters 
Opposition Opposition Team 
Player Player 
R50 Rebound 50s 
SC Super Coach Points 
SCL Stoppage Clearances 
SI Score Involvements 
Status todo 
T Tackles 
T5 Tackles Inside 50 
TO Turnovers 
TOG Time On Ground 
Team Team 
UP Uncontested Possessions 
Venue Venue

<dt>AF</dt><dd><p>AFL Fantasy Points</p></dd>
<dt>B</dt><dd><p>Behinds</p></dd>
<dt>BO</dt><dd><p>Bounces</p></dd>
<dt>CCL</dt><dd><p>Centre Clearances</p></dd>
<dt>CG</dt><dd><p>Clangers</p></dd>
<dt>CL</dt><dd><p>Clearances</p></dd>
<dt>CM</dt><dd><p>Contested Marks</p></dd>
<dt>CP</dt><dd><p>Contested Possessions</p></dd>
<dt>D</dt><dd><p>Disposals</p></dd>
<dt>DE</dt><dd><p>Disposal Efficiency %</p></dd>
<dt>ED</dt><dd><p>Effective Disposals</p></dd>
<dt>FA</dt><dd><p>Frees Against</p></dd>
<dt>FF</dt><dd><p>Frees For</p></dd>
<dt>G</dt><dd><p>Goals</p></dd>
<dt>GA</dt><dd><p>Goal Assists</p></dd>
<dt>GA1</dt><dd><p>Goal Assists on Advanced Page</p></dd>
<dt>HB</dt><dd><p>Handballs</p></dd>
<dt>HO</dt><dd><p>Hit Outs</p></dd>
<dt>I50</dt><dd><p>Inside 50</p></dd>
<dt>ITC</dt><dd><p>Intercepts</p></dd>
<dt>K</dt><dd><p>Kicks</p></dd>
<dt>M</dt><dd><p>Marks</p></dd>
<dt>MG</dt><dd><p>Metres Gained</p></dd>
<dt>MI5</dt><dd><p>Marks Inside 50</p></dd>
<dt>Match_id</dt><dd><p>Match ID</p></dd>
<dt>One.Percenters</dt><dd><p>One Percenters</p></dd>
<dt>Opposition</dt><dd><p>Opposition Team</p></dd>
<dt>Player</dt><dd><p>Player</p></dd>
<dt>R50</dt><dd><p>Rebound 50s</p></dd>
<dt>SC</dt><dd><p>Super Coach Points</p></dd>
<dt>SCL</dt><dd><p>Stoppage Clearances</p></dd>
<dt>SI</dt><dd><p>Score Involvements</p></dd>
<dt>Status</dt><dd><p>todo</p></dd>
<dt>T</dt><dd><p>Tackles</p></dd>
<dt>T5</dt><dd><p>Tackles Inside 50</p></dd>
<dt>TO</dt><dd><p>Turnovers</p></dd>
<dt>TOG</dt><dd><p>Time On Ground</p></dd>
<dt>Team</dt><dd><p>Team</p></dd>
<dt>UP</dt><dd><p>Uncontested Possessions</p></dd>
<dt>Venue</dt><dd><p>Venue</p></dd>

**Comment by jimmyday12** [comment]
Thanks @joffa101 - I'll look to add them to the documentation

**Comment by jimmyday12** [comment]
I'm in the process of removing internal data from the package in favour of using the functions the access the data (the package is currently too large for CRAN). As such, I won't document these for now as part of the package, although may revisit in a vignette.
