### ISSUE TITLE
Unfiltered cancelled matches result in NA match dates

### ISSUE THREAD

**Issue by cfranklin11** [jimmyday12/fitzRoy#56]
The [2015 fixture](https://www.footywire.com/afl/footy/ft_match_list?year=2015) has a match in round 14 that was cancelled, resulting in two rows without dates. Given that these are labelled 'MATCH CANCELLED' in the same place where teams' bye rounds are labelled 'BYE', I think it makes sense to add that as a condition to the bye match filter in `get_fixture` to avoid invalid match rows.

If the proposed fix sounds good, I'm happy to open a PR to make the change.

**Comment by jimmyday12** [comment]
@cfranklin11 Good pickup - happy for a PR!
