### ISSUE TITLE
Adding of a general player table from footywire. 

### ISSUE THREAD

**Issue by trevorbix** [jimmyday12/fitzRoy#60]
It would be great if we could have a general table which includes information such as D.O.B, Position, Weight, Height, Draft Pick etc. 

The data lives here (pp - player profile)

[https://www.footywire.com/afl/footy/pp-essendon-bombers--joshua-begley](url)

Apologies if this exists, I had a good look but couldn't locate.

**Comment by jimmyday12** [comment]
Hmmm this would be simple enough to write a scraper for one player but having it all together is another matter. I'll have to think about this one

**Comment by anoafl** [comment]
can lift most of the script here
https://analysisofafl.netlify.com/data/2018-11-24-getting-player-information/

only issue is that for retired players the page structure changes slightly, 
secondly need to think a little about how to structure team (as people have played for mutliple teams)

**Comment by trevorbix** [comment]
Past Players have their own section:

https://www.footywire.com/afl/footy/past_players

In which modern past players have a similar profile:

![image](https://user-images.githubusercontent.com/10975303/52756422-e120cf80-3033-11e9-8cd5-3a82e5f6d844.png)

![image](https://user-images.githubusercontent.com/10975303/52756463-01e92500-3034-11e9-886e-43c9beb1caba.png)

but one tricky bit is for older players, we lose info:

![image](https://user-images.githubusercontent.com/10975303/52756575-660be900-3034-11e9-9061-f1c7f947483c.png)

No draft info (pre draft I guess), no games played (we can calculate that), and no position. 

So really - it's only position thats missing. 

I think having Last/Current Team would be fine for the column?

**Comment by anoafl** [comment]
That's what I meant the page structure changes slightly, so the 
playing.for<-  page%>%
    html_nodes(".ldrow a b")%>%

would change slightly

**Comment by anoafl** [comment]
oh and the last thing would be a function to update as players debut and their information starts to get filled out for example:

https://www.footywire.com/afl/footy/pp-carlton-blues--sam-walsh

**Comment by trevorbix** [comment]
Very good point. Might be able to get around by looking to see if they have played any games as a cursory look?

![image](https://user-images.githubusercontent.com/10975303/52786063-6b951d80-308c-11e9-8010-5cfff502f28d.png)

If that flag fails - normal scrape for an active player, and so on?

**Comment by anoafl** [comment]
maybe, but you also have players like
https://www.footywire.com/afl/footy/pp-kangaroos--declan-watson

that have info without games. 

then you also have

https://www.footywire.com/afl/footy/pp-carlton-blues--michael-gibbons

its something I'd really like to add, just need to think about the best capture method going backwards and then probably need to see how the pages work in season for the new players as well.

**Comment by trevorbix** [comment]
uh yeah, thats super tricky. I will have a think

**Comment by jimmyday12** [comment]
This is now in the new `fetch_player_details` function
