### ISSUE TITLE
footywire has changed format

### ISSUE THREAD

**Issue by jimmyday12** [jimmyday12/fitzRoy#61]
footywire has updated their site and so some of the scrapers are broken. 

```r
get_match_data(5000)
 Error: Table has inconsistent number of columns. Do you want fill = TRUE? 
```

**Comment by dstatz** [comment]
would this be why the footywire advanced player stats from the 2018 finals isn't coming through?

**Comment by jimmyday12** [comment]
Possibly. Are you able to create a new issue on here @dstatz with a reproducible example?

**Comment by anoafl** [comment]
fitzRoy::player_stats (only goes to end of home and away 2018)

but if you did

fitzRoy::get_footywire_stats(9720)

That works fine for the grand final

hope that helps @dstatz

**Comment by dstatz** [comment]
Shall do :)

**Comment by dstatz** [comment]
@jimmyday12 no problem shall do!

@anoafl thanks! I just tried that unfortunately not working for me either :( here's what I got:

`> > fitzRoy::get_footywire_stats(9720)`
`Getting data from footywire.com`
`Error: Table has inconsistent number of columns. Do you want fill = TRUE?`

**Comment by anoafl** [comment]
Are you updated with latest Fitzroy?

**Comment by dstatz** [comment]
@anoafl yep that was it, updated and the above error was resolved, thanks!
