### ISSUE TITLE
AFLTables Extract Has Non-Unique Home.team for Drawn Finals

### ISSUE THREAD

**Issue by TonyCorke** [jimmyday12/fitzRoy#71]
Please briefly describe your problem and what output you expect. 

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Extract from AFLTables produces rows with two teams as home team for drawn Finals. Each game should have a single, unique, Home.team

```r
``` r
library(fitzRoy)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

stats = get_afltables_stats(start_date = "1897-01-01", end_date = "2019-06-01") 
#> Returning data from 1897-01-01 to 2019-06-01
#> Finished getting afltables data
stats$Date_proper = as.Date(stats$Date, format = "%d/%m/%Y")
ss = stats %>% group_by(Date_proper, Venue, Local.start.time, Round) %>% summarise(NumGames = length(unique(Home.team)))
ss %>% filter(NumGames > 1)
#> # A tibble: 8 x 5
#> # Groups:   Date_proper, Venue, Local.start.time [8]
#>   Date_proper Venue         Local.start.time Round NumGames
#>   <date>      <chr>                    <int> <chr>    <int>
#> 1 1928-09-15  M.C.G.                    1430 SF           2
#> 2 1946-09-14  M.C.G.                    1430 SF           2
#> 3 1948-10-02  M.C.G.                    1450 GF           2
#> 4 1962-09-15  M.C.G.                    1430 PF           2
#> 5 1972-09-16  Waverley Park             1430 SF           2
#> 6 1977-09-24  M.C.G.                    1450 GF           2
#> 7 1990-09-08  Waverley Park             1430 QF           2
#> 8 2010-09-25  M.C.G.                    1430 GF           2
```

<sup>Created on 2019-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

```

**Comment by jimmyday12** [comment]
Hi @TonyCorke - struggling to get my head around this one (trying to attack this late at night maybe not the best idea!). Just want to make sure I've captured this properly.

It seems as though the drawn game has been scraped twice - one with the correct home team and the other with the teams switched around. So for example, the 2010 GF, has 22 rows with Collingwood as the Home Team and 22 rows with St Kilda as the home team on the same date, with the same statistics.  

The 'replayed' game seems to get scraped fine on the correct date without duplicates. 

Sound right?

**Comment by TonyCorke** [comment]
Yes. That's what I found.

Paul makes the winning team the "home team" in all Finals (as I understand
it), which is probably why we get this duplication for the draws (as there
are two "winning teams").

It'd be great to fix this broader issue of defining home team for Finals at
some point, but for now I guess we just fix these dupes.

TC

**Comment by jimmyday12** [comment]
Ah interesting. Yeah - I think I'll contact Paul on things like that for now. I do have some general thoughts around maybe some helper functions to fix any errors/issues with afltables to allow people to fix them if they want.

For now will fix the duplicates!

**Comment by jimmyday12** [comment]
I think this should be fixed in the latest commit but would appreciate any testing @TonyCorke! https://github.com/jimmyday12/fitzRoy/commit/c160cc577e1b52d8548cdabdb2de77d243a7eac4
