### ISSUE TITLE
Corrupt RDB after recent update (27/06)

### ISSUE THREAD

**Issue by SolveWebb** [jimmyday12/fitzRoy#75]
Hi guys,

I had an issue this morning which appears to have resolved itself now, but I will document in case it is only latent. 

My code updated fitZroy, and then I received an error (sorry, I didn't save it) and the general gist was that the fitzRoy.rds file was corrupted and I couldn't download the newest statistics from AFL tables. 

I updated all my of my packages and it worked, so I predict it was some sort of dependency that broke in whatever changed, but I am not sure. 

Sorry I don't have any more details! It did happen on two laptops, if that helps. It's all good now. 

Liam

**Comment by jimmyday12** [comment]
Thanks @SolveWebb - I have seen this before in another package I think. It seems to be sometimes a package file gets corrupt based on some dependency. 

I'll keep an eye out for it, thanks for reporting!
