### ISSUE TITLE
Values on AFL Tables don't match export

### ISSUE THREAD

**Issue by SolveWebb** [jimmyday12/fitzRoy#78]
Hi Guys,

I was just doing a merge between the AT data and the AFL website data and I noticed some slight discrepencies between the two datasets, on most of the variables. Normally only 1 or 2 difference, so I assumed maybe AT had a different stats provider to the AFL website. When i checked it for a specific example, I noticed something odd though:

Jaeger O'Meara R 3 this year versus Kangaroos. 

![image](https://user-images.githubusercontent.com/38903690/62591004-8a74be00-b911-11e9-9c3c-78e74fdb37cb.png)

16 Kicks, 15 Handballs and 3 Marks

AFL Website:

![image](https://user-images.githubusercontent.com/38903690/62591044-b001c780-b911-11e9-97e6-63c8ee98d706.png)

17 Kicks, 14 handballs and 3 marks

AFL TABLES

![image](https://user-images.githubusercontent.com/38903690/62591069-c3149780-b911-11e9-90c8-065726677c06.png)

17 Kicks, 15 Handballs and 3 marks. 

they are all different!!

**Comment by jimmyday12** [comment]
Should be fixed by https://github.com/jimmyday12/fitzRoy/pull/223
