### ISSUE TITLE
get_afltables_stats() returns data with some players in incorrect teams and seasons

### ISSUE THREAD

**Issue by neilfws** [jimmyday12/fitzRoy#82]
I'm using R 3.6.1 and fitzRoy 0.1.13.9000 on Mac OS X.

This code:

```
library(dplyr)
library(fitzRoy)

afl <- fitzRoy::get_afltables_stats()
afl %>% 
  count(Season, Playing.for, ID, First.name, Surname) %>% 
  group_by(ID) %>% 
  filter(Season == max(Season) | Season == min(Season), 
         last(Season) - first(Season) > 25) %>% 
  arrange(ID)
```

returns this:

```
# A tibble: 6 x 6
# Groups:   ID [3]
  Season Playing.for       ID First.name Surname      n
   <dbl> <chr>          <dbl> <chr>      <chr>    <int>
1   1900 Geelong            0 Heber      Quinton      1
2   2018 Brisbane Lions     0 Heber      Quinton     22
3   1907 Collingwood     3500 Albert     Pannam       2
4   1947 Richmond        3500 Albert     Pannam       2
5   1907 Geelong        10665 Peter      Stephens     1
6   1973 Geelong        10665 Peter      Stephens    11
```

According to afltables.com Heber Quinton played 1 game for Geelong only. There are two players named Albert Pannam who have been assigned the same ID (3500). There are also two Peter Stephens, who both played for Geelong and have the same ID (10665).

Note that the code returns only first + last seasons by player. There are additional records _e.g._ Heber Quinton is also incorrectly linked with 1 game for Fitzroy in 1901.

**Comment by SingSing2020** [comment]
The stats for Heber Quinton (the 22 games for Brisbane) is actually Cam Rayner stats

AFL_download %>%
  mutate(First.name = case_when(First.name == "Heber" & Surname == "Quinton" ~ "Cam",
                                TRUE ~ First.name)) %>%
  mutate(Surname = case_when(First.name == "Cam" & Surname == "Quinton"  ~ "Rayner",
                             TRUE ~ Surname)) %>%
  mutate(ID = case_when(ID == "0"  ~ "12592",
                        TRUE ~ ID)) %>%
  mutate(Playing.for = case_when(ID == "12592" ~ "Brisbane Lions",
                                 TRUE ~ Playing.for)) -> AFL_download

**Comment by jimmyday12** [comment]
https://github.com/jimmyday12/fitzRoy/pull/223
