### ISSUE TITLE
Add Ladder function

### ISSUE THREAD

**Issue by jimmyday12** [jimmyday12/fitzRoy#85]
There should be an easy function to return the AFL ladder for any round. The Squiggle API does a decent job back to round 2011

**Comment by JaseZiv** [comment]
I have a function that might do this... it takes in a data frame obtained using `get_match_results()` and can return results from all regular season rounds and all seasons, or be limited to certain round(s) and season(s).

Any interest in this?

**Comment by jimmyday12** [comment]
@JaseZiv Yep certainly some interest. My initial thoughts were just writing a scraper but your approach could be feasible too and possibly faster since get_match_results() is relatively quick to scrape.

**Comment by JaseZiv** [comment]
@jimmyday12 Ok great. I've got the function ready so I'll write some docs and create a pull request tomorrow hopefully and you can let me know your thoughts.

**Comment by jimmyday12** [comment]
Fixed by 45d7b0d9d36327647b4b6956fb848af8a1ee13f0
