### ISSUE TITLE
AFLW player statistics

### ISSUE THREAD

**Issue by dicook** [jimmyday12/fitzRoy#86]
Would it be possible to add functionality to get the player statistics for the AFLW?

**Comment by anoafl** [comment]
Should be possible, I will look into it

**Comment by OscarLane** [comment]
I looked into this a while ago and it seemed possible as the offical stats site hosted individual player stats, but it appears that they've been removed: [https://www.afl.com.au/womens/matches/stats](https://www.afl.com.au/womens/matches/stats). The page is called AFLW Player & Match Statistics, but only has a tab for team stats where there used to be one for players as well.

**Comment by jimmyday12** [comment]
This is now largely completed with the addition of the `fetch_stats` functions in the upcoming 1.0.0 release (or 0.3.3.9000 development version)
