### ISSUE TITLE
AFLW cookie not working

### ISSUE THREAD

**Issue by jimmyday12** [jimmyday12/fitzRoy#97]
Likely a repeat of #62. I suspect the Cookie has changed again. 

We need two fixes
1 - update the cookie code to find the right place
2 - handle the Vignette if the cookie fails to load. We already handle this ok in tests. 

``` r
cookie <- get_aflw_cookie()
#> Error in get_aflw_cookie(): could not find function "get_aflw_cookie"
```

<sup>Created on 2019-12-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jimmyday12** [comment]
@OscarLane - looks like the cookie has moved again. In fact - I think the whole AFL womens stats page has been taken down? 

https://www.afl.com.au/womens/matches/stats

**Comment by merbla** [comment]
I found this as well, the entire AFL.com.au structure has changed.
